[tool.poetry]
name = "presaber"
version = "0.1.0"
description = ""
authors = ["estebandurangov <esteban.durangov@udea.edu.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
